Run emotions classifier locally
golemfactory/galatea pull request #1
Opened 2021-04-15 15:40 UTC by Wiezzel

## Run classifier locally

### 0. Prepare environment

```bash
$ cd provider
$ python3 -m venv .venv
$ . .venv/bin/activate
$ pip install -r requirements.txt
```

### 1. Download model

```bash
$ python download_model.py nateraw/bert-base-uncased-emotion ./models/emotion
```

### 2. Run the classifier

```bash
$ python run_classifier.py ./models/emotion/ ./the_queen_sample.txt ./output.txt
$ cat output.txt 
{'sadness': 0.19551274180412292, 'joy': 0.6668532490730286, 'love': 0.061145614832639694, 'anger': 0.051483768969774246, 'fear': 0.02209818735718727, 'surprise': 0.0029064537957310677}
```

2021-04-16 09:31 UTC, pnowosie approved these changes
Works exactly as described in readme.
Kudos for following branch naming convention.

Great work!

2021-04-19 08:20 UTC, johny-b commented on provider/download_model.py
> +    except KeyError:
```suggestion
    except ValueError:
```

2021-04-19 08:22 UTC, johny-b requested changes

2021-04-19 08:22 UTC, johny-b commented on provider/run_classifier.py
> +    except (KeyError, TypeError):
```suggestion
    except (ValueError, TypeError):
```

2021-04-19 08:27 UTC, johny-b approved these changes

2021-04-19 08:43 UTC, merged